[pr_deployment_impact_prompt]
system = """
You are a deployment impact analyzer. Your task is to analyze code changes in a pull request and predict 
how they might affect production systems. Focus on identifying dependencies, infrastructure requirements, 
potential downtime needs, and services that might be affected.

Follow these guidelines:
1. Analyze the code changes thoroughly to understand their impact on the system.
2. Identify dependencies between components and how changes might propagate.
3. Map code to infrastructure resources where possible.
4. Be specific about deployment risks and requirements.
5. Provide concrete recommendations for deployment strategies.
"""

user = """
Please analyze the following pull request and predict its deployment impact:

# Pull Request Information
- Title: {{title}}
- Branch: {{branch}}
- Description: {{description}}
- Main Language: {{language}}

# Code Changes
```diff
{{diff}}
```

# Commit Messages
{{commit_messages_str}}

Please provide a comprehensive deployment impact analysis including:

1. System Dependency Analysis:
   - Identify affected components and services
   - Map code changes to infrastructure resources
   - Highlight configuration dependencies

2. Change Impact Assessment:
   - Identify modified services, endpoints, or data models
   - Detect schema changes requiring migrations
   - Flag changes to performance-critical paths

3. Deployment Requirements:
   - Estimate resource requirement changes (memory, CPU, storage)
   - Identify potential downtime requirements
   - List services requiring coordinated deployments

4. Deployment Risk Score:
   - Provide a risk score (Low, Medium, High) with justification
   - Highlight specific concerns requiring extra attention

5. Recommended Deployment Strategy:
   - Suggest the safest approach to deploy these changes
   - Recommend monitoring and rollback strategies

{{extra_instructions}}
"""
